shell.run('clear')
print('!!! DO NOT TOUCH !!!')
print('')
print('For chunk loading only!')
print('')
print('You WILL break stuff if you:')
print('')
print('break ...')
print('shutdown ...')
print('take away ...')
print('')
print('... this turtle.')
